#!/usr/bin/python

import csv

from pandas import read_csv

#df = read_csv('soc-sign-bitcoinalpha.csv')
#df.columns=['source','target','rating','time']
#df.to_csv('soc-sign-bitcoinalpha-label.csv')

myDict = {}

with open('./testfile.csv', newline='' ) as File : 
    #reader = csv.reader(File)
    reader = csv.DictReader(File)
    for row in reader:
        #print (row['source'], row['target'])
        key = row['source']
        value = row['target']
        myDict['key'].append(value)

print (myDict)
        #if (row['source'] =  )
